name: Deploy to FirstVDS

on:
  push:
    branches: [ main ] # Если ваша ветка называется master, замените main на master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/rgsu_bot
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart rgsubot
